package com.antgskds.calendarassistant.feature.backup.courseimport

import com.antgskds.calendarassistant.feature.backup.courseimport.external.wakeup.WakeUpShareClient
import com.antgskds.calendarassistant.feature.backup.courseimport.external.wakeup.WakeUpShareProtocol
import io.ktor.client.HttpClient
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.http.HttpStatusCode
import io.ktor.http.content.OutgoingContent
import io.ktor.http.parseQueryString
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.*
import org.junit.Test

/** Fixtures were generated by the pinned upstream Python implementation using synthetic courses. */
class WakeUpShareProtocolTest {
    private val fixture = javaClass.getResourceAsStream("/wakeupdecoder/reference.json")!!.use {
        Json.parseToJsonElement(it.bufferedReader(Charsets.UTF_8).readText()).jsonObject
    }
    private fun value(name: String) = fixture.getValue(name).jsonPrimitive.content

    @Test fun signatureAndCiphertextMatchUpstreamReference() {
        assertEquals(value("cuid"), WakeUpShareProtocol.cuid)
        assertEquals(value("adid"), WakeUpShareProtocol.adid)
        assertEquals(value("sign_a"), WakeUpShareProtocol.makeSignA(value("rand10")))
        assertEquals(value("token"), WakeUpShareProtocol.tokenFromSignB(value("sign_b"), value("rand10")))
        val request = WakeUpShareProtocol.buildShareRequest(
            "synthetic-fixture-code", value("token"), 1780000000, 123456
        )
        assertEquals(value("rc4_key"), request.rc4Key)
        assertEquals(value("request_body"), request.body)
        val parsed = parseQueryString(request.body.removePrefix("&"))
        assertEquals(value("request_data"), parsed["data"])
        assertEquals(value("request_sign"), parsed["sign"])
    }

    @Test fun decryptedResponseFeedsExistingCourseParser() {
        val decoded = WakeUpShareProtocol.decryptShareData(value("encrypted_response"), value("rc4_key"))
        val shareData = Json.parseToJsonElement(decoded).jsonObject.getValue("shareData").jsonPrimitive.content
        assertEquals(value("share_data"), shareData)
        val parsed = CourseImportParser.parseWakeUpShareData(shareData)
        assertEquals("2026-09-07", parsed.semesterStartDate)
        assertEquals(16, parsed.totalWeeks)
        assertEquals(2, parsed.timeNodeCount)
        val course = parsed.courses.single()
        assertEquals("测试课程", course.name)
        assertEquals("测试老师", course.teacher)
        assertEquals("测试教室", course.location)
        assertEquals(1, course.startNode)
        assertEquals(2, course.endNode)
    }

    @Test fun authenticationRejectsWrongChallengeAndMalformedCiphertext() {
        assertThrows(IllegalArgumentException::class.java) {
            WakeUpShareProtocol.tokenFromSignB(value("sign_b"), "OtherRand1")
        }
        assertThrows(IllegalArgumentException::class.java) {
            WakeUpShareProtocol.tokenFromSignB("not-valid-hex", value("rand10"))
        }
        assertThrows(IllegalArgumentException::class.java) {
            WakeUpShareProtocol.makeSignA("short")
        }
    }

    @Test fun signedNetworkFlowPreservesThePreviewContent() = runBlocking {
        val paths = mutableListOf<String>()
        val engine = MockEngine { request ->
            paths += request.url.encodedPath
            assertEquals("api.wakeup.fun", request.url.host)
            assertEquals("POST", request.method.value)
            assertEquals(value("cuid"), request.headers["zyb-cuid"])
            assertEquals(value("adid"), request.headers["zyb-adid"])
            val body = (request.body as OutgoingContent.ByteArrayContent).bytes().toString(Charsets.UTF_8)
            when (request.url.encodedPath) {
                "/pluto/app/antispam" -> {
                    assertEquals(value("sign_a"), parseQueryString(body)["data"])
                    respond("""{"errNo":0,"data":{"data":"${value("sign_b")}"}}""")
                }
                "/share_schedule/getv2" -> {
                    assertEquals(value("request_data"), parseQueryString(body.removePrefix("&"))["data"])
                    respond("""{"errNo":0,"data":{"data":"${value("encrypted_response")}"}}""")
                }
                else -> error("Unexpected endpoint")
            }
        }
        HttpClient(engine).use { client ->
            assertEquals(value("share_data"), WakeUpShareClient(client).fetchShareData(
                "synthetic-fixture-code", value("rand10")
            ))
        }
        assertEquals(listOf("/pluto/app/antispam", "/share_schedule/getv2"), paths)
    }

    @Test fun expiredSharesAndAuthenticationFailuresRemainFailures() = runBlocking {
        for (failureAt in listOf(1, 2)) {
            var calls = 0
            val engine = MockEngine {
                calls++
                if (calls == failureAt) respond("""{"errNo":7,"errMsg":"分享口令已失效"}""")
                else respond("""{"errNo":0,"data":"${value("sign_b")}"}""")
            }
            HttpClient(engine).use { client ->
                val failure = runCatching {
                    WakeUpShareClient(client).fetchShareData("synthetic-fixture-code", value("rand10"))
                }.exceptionOrNull()
                assertTrue(failure is IllegalStateException)
                assertEquals("分享口令已失效", failure?.message)
            }
            assertEquals(failureAt, calls)
        }
    }

    @Test fun invalidResponsesExplainFailureWithoutReturningRawPayload() = runBlocking {
        for (body in listOf("invalid-json", """{"errNo":0,"data":"broken-ciphertext"}""")) {
            val engine = MockEngine { respond(body) }
            HttpClient(engine).use { client ->
                val failure = runCatching {
                    WakeUpShareClient(client).fetchShareData("synthetic-fixture-code", value("rand10"))
                }.exceptionOrNull()
                assertTrue(failure?.message.orEmpty().contains("从文件"))
                assertFalse(failure?.message.orEmpty().contains(body))
            }
        }
        val engine = MockEngine { respond("", HttpStatusCode.ServiceUnavailable) }
        HttpClient(engine).use { client ->
            val failure = runCatching {
                WakeUpShareClient(client).fetchShareData("synthetic-fixture-code", value("rand10"))
            }.exceptionOrNull()
            assertEquals("WakeUp 请求失败：HTTP 503", failure?.message)
        }
    }

    @Test fun coroutineCancellationIsNotConvertedIntoAnImportError() = runBlocking {
        val engine = MockEngine { throw CancellationException("cancelled") }
        HttpClient(engine).use { client ->
            val failure = runCatching {
                WakeUpShareClient(client).fetchShareData("synthetic-fixture-code", value("rand10"))
            }.exceptionOrNull()
            assertTrue(failure is CancellationException)
        }
    }
}
